#!/bin/sh

PREFIX=
. "$PREFIX/lib/libalpine.sh"

conf="$ROOT/etc/sendbug/sendbug.conf"

cfgval() {
	awk -F= "/^$1/ {print \$2}" "$ROOT/etc/ssmtp/ssmtp.conf" 2>/dev/null
}

email=$(awk -F= '/^mailfrom/ {print $2}' "$conf" 2>/dev/null)

if [ -z "$email" ] ; then
	hostname=$(cfgval hostname)
	if [ -z "$hostname" ]; then
		hostname=$(hostname -f 2>/dev/null || cat /etc/hostname)
	fi
else
	hostname=$(hostname -f 2>/dev/null || cat /etc/hostname)
fi
domain=$(hostname -d $hostname 2>/dev/null)
if [ -n "$hostname" -a -z "$email" ] ; then
	email=$(whoami)@$hostname
fi

echon "Sender email address for problem reports? [$email] "
default_read email $email

if grep ^mailfrom "$conf" > /dev/null 2>&1; then
	sed -i "s/^mailfrom.*/mailfrom=$email/" "$conf"
else
	mkdir -p $(dirname "$conf")
	echo "mailfrom=$email" >> "$conf"
fi

setup-mta

echo ""
echo "Please run 'sendbug' to submit problem reports"

