#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	fake_adduser_usage \
	fake_adduser_failure

fake_adduser_usage_body() {
	init_env
	atf_check -s exit:0 \
		-e match:"Usage: adduser" \
		adduser --help
}

fake_adduser_failure_body() {
	init_env
	ADDUSER_EXIST=juser atf_check -s exit:1 \
		-e match:"adduser: user 'juser' in use" \
		adduser juser
}

