#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	fake_wget_usage \
	fake_wget_spider \
	fake_wget_quiet \
	fake_wget \
	fake_wget_outfile \
	fake_wget_stdout \
	fake_wget_fail \
	fake_wget_404 \
	fake_wget_missing_url \
	fake_wget_empty_url

fake_wget_usage_body() {
	test_usage wget
}

fake_wget_spider_body() {
	init_env
	atf_check -s exit:0 \
		-o empty \
		-e empty \
		wget --spider https://example.com
}

fake_wget_quiet_body() {
	init_env
	atf_check -s exit:0 \
		-o empty \
		-e empty \
		wget -q https://example.com
}

fake_wget_body() {
	init_env
	atf_check -s exit:0 \
		-o empty \
		-e match:"saving to 'index.html'" \
		wget https://example.com
		test -f index.html || atf_fail "index.html not created"
}

fake_wget_outfile_body() {
	init_env
	atf_check -s exit:0 \
		-o empty \
		-e match:"saving to 'foo'" \
		wget -O foo https://example.com
		test -f foo || atf_fail "foo not created"
}

fake_wget_stdout_body() {
	init_env
	export WGETCONTENT="hello world"
	atf_check -s exit:0 \
		-o match:"hello world" \
		-e match:"writing to stdout" \
		wget -O - https://example.com
		! test -f - || atf_fail "- was created"
}

fake_wget_fail_body() {
	init_env
	atf_check -s exit:1 \
		-e match:"bad address" \
		wget https://example.com/fail
}

fake_wget_404_body() {
	init_env
	atf_check -s exit:1 \
		-e match:"404 Not Found" \
		wget https://example.com/404
}

fake_wget_missing_url_body() {
	init_env
	atf_check -s exit:1 \
		-e match:"usage:" \
		wget -q -O -
}

fake_wget_empty_url_body() {
	init_env
	atf_check -s exit:1 \
		-e match:"bad address" \
		wget ""
}

