#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	setup_xen_dom0

setup_xen_dom0_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"modprobe xen" \
		-o match:"Starting xen" \
		-e empty \
		setup-xen-dom0
}

