#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	setup_user_usage \
	setup_user_fullname \
	setup_user_interactive \
	setup_user_interactive_fullname

setup_user_usage_body() {
	test_usage setup-user
}

setup_user_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"adduser -D testuser" \
		-e empty \
		setup-user testuser
}

setup_user_fullname_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"adduser.* -D .*testuser" \
		-o match:"adduser.* -g Joe User .*testuser" \
		-e empty \
		setup-user -f "Joe User" testuser
}

setup_user_interactive_body() {
	init_env
	(
		echo "Joe User"
		echo "testuser"
		echo "none"
	) | atf_check -s exit:0 \
		-o match:"Enter full name" \
		-o match:"Enter username" \
		-o not-match:"adduser.* -D .*testuser" \
		-o match:"adduser.* -g Joe User .*testuser" \
		-e empty \
		setup-user
}

setup_user_interactive_fullname_body() {
	init_env
	(
		echo "testuser"
	) | atf_check -s exit:0 \
		-o not-match:"Enter full name" \
		-o match:"Enter username" \
		-o not-match:"adduser.* -D .*testuser" \
		-o match:"adduser.* -g Joe User .*testuser" \
		-e empty \
		setup-user -f "Joe User" -k none
}

