#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	setup_keymap_usage \
	setup_keymap_none \
	setup_keymap_existing_keymap_default

setup_keymap_usage_body() {
	test_usage setup-keymap
}

setup_keymap_none_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"apk add.*keymap" \
		setup-keymap none
}

setup_keymap_existing_keymap_default_body() {
	init_env
	fake_bin apk <<-__EOF__
		#!/bin/sh
		exit 0
	__EOF__

	mkdir -p etc/conf.d usr/share/bkeymaps/us
	echo 'KEYMAP=/etc/keymap/us.bmap' > etc/conf.d/loadkmap
	: > usr/share/bkeymaps/us/us.bmap
	: > usr/share/bkeymaps/us/dvorak.bmap

	printf "abort\nabort\n" >answers

	atf_check -s exit:0 \
		-o ignore \
		-e empty \
		sh -c 'setup-keymap us < answers'
	atf_check -s exit:0 test -f etc/keymap/us.bmap
}
