#!/usr/bin/env atf-sh

init_env() {
	PATH=$(atf_get_srcdir)/..:$PATH
	export ROOT=$PWD LIBDIR=$(atf_get_srcdir)/.. MOCK=echo
}

# docs:
# - https://github.com/jmmv/kyua/wiki/Quickstart-atf-sh-test
# - https://manned.org/atf-sh-api

atf_init_test_cases() {
	atf_add_test_case setup_hostname_usage
}

atf_test_case setup_hostname_usage
setup_hostname_usage_body() {
	init_env
	atf_check -s exit:0 \
		-o match:'^usage: setup-hostname' \
		-e empty \
		setup-hostname -h
}

