#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	setup_desktop_usage \
	setup_desktop_unsupported \
	setup_desktop_xfce \
	setup_desktop_gnome \
	setup_desktop_plasma \
	setup_desktop_mate \
	setup_desktop_sway

setup_desktop_usage_body() {
	test_usage setup-desktop
}

setup_desktop_unsupported_body() {
	init_env
	atf_check -s exit:1 \
		-o empty \
		-e match:"usage" \
		setup-desktop blah
}

setup_desktop_xfce_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"apk add.*xfce4" \
		-o match:"Starting udev" \
		-e match:"WARNING: You need to create a user account" \
		setup-desktop xfce
}

setup_desktop_gnome_body() {
	init_env
	mkdir -p etc/apk
	echo "https://example.tld/main" > etc/apk/repositories
	atf_check -s exit:0 \
		-o match:"apk add.*gnome" \
		-o match:"Starting udev" \
		-e match:"WARNING: You need to create a user account" \
		setup-desktop gnome
}

setup_desktop_plasma_body() {
	init_env
	mkdir -p etc/apk
	echo "https://example.tld/main" > etc/apk/repositories
	atf_check -s exit:0 \
		-o match:"apk add.*plasma-desktop" \
		-o match:"Starting udev" \
		-e match:"WARNING: You need to create a user account" \
		setup-desktop plasma
}

setup_desktop_mate_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"apk add.*mate-desktop" \
		-o match:"Starting udev" \
		-e match:"WARNING: You need to create a user account" \
		setup-desktop mate
}

setup_desktop_sway_body() {
	init_env
	atf_check -s exit:0 \
		-o match:"apk add.*sway" \
		-o match:"Starting udev" \
		-e match:"WARNING: You need to create a user account" \
		setup-desktop sway
}
