#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	setup_timezone_usage \
	setup_timezone_copy \

setup_timezone_usage_body() {
	test_usage setup-timezone
}

setup_timezone_copy_body() {
	init_env
	mkdir -p usr/share/zoneinfo/Europe
	touch usr/share/zoneinfo/Europe/Oslo
	atf_check -s exit:0 \
		-o match:"apk add .*tzdata" \
		-o match:"apk del" \
		-e empty \
		setup-timezone Europe/Oslo
}

